//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.13 at 09:24:58 AM CET 
//


package ua.nure.romenskiy.lab2.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Prop complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Prop"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Material" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Trunk" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Haft" type="{http://nure.ua/romenskiy/Lab2/entity}parent"/&gt;
 *         &lt;element name="MagSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Prop", propOrder = {
    "name",
    "material",
    "trunk",
    "haft",
    "magSize"
})
public class Prop {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Material", required = true)
    protected String material;
    @XmlElement(name = "Trunk", required = true)
    protected String trunk;
    @XmlElement(name = "Haft", required = true)
    protected Parent haft;
    @XmlElement(name = "MagSize")
    protected int magSize;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the trunk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrunk() {
        return trunk;
    }

    /**
     * Sets the value of the trunk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrunk(String value) {
        this.trunk = value;
    }

    /**
     * Gets the value of the haft property.
     * 
     * @return
     *     possible object is
     *     {@link Parent }
     *     
     */
    public Parent getHaft() {
        return haft;
    }

    /**
     * Sets the value of the haft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parent }
     *     
     */
    public void setHaft(Parent value) {
        this.haft = value;
    }

    /**
     * Gets the value of the magSize property.
     * 
     */
    public int getMagSize() {
        return magSize;
    }

    /**
     * Sets the value of the magSize property.
     * 
     */
    public void setMagSize(int value) {
        this.magSize = value;
    }

}
